---
name: Firmware build

on:
  push:
    branches: [ 'custom' ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false
      

permissions:
  contents: read

jobs:

  # Builds with DFU_UPDATE_BUILD=1        
  build_dfu:
    runs-on: ubuntu-20.04
    strategy:
      # devices to build for
      matrix:
        board: [PUCKJS, PUCKJS_MINIMAL]
      # try and build for all devices even if one fails
      fail-fast: false 
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    
    - name: make ${{ matrix.board }}
      env:
        TRAVIS: 1
        RELEASE: 1
        DFU_UPDATE_BUILD: 1
        BOARD: ${{ matrix.board }}
      run: |
        source ./scripts/provision.sh  ${{ matrix.board }}
        make     
    - name: Upload ${{ matrix.board }} build artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: ${{ matrix.board }}
        path: |
          bin/*.bin
          bin/*.hex
          bin/*.tgz
          bin/*.zip
